[{
    "name": "Toallon Seleccion",
    "description": "Microfibra. 100% Poliester. 120cm X 169cm.",
    "img": ['https://i.ibb.co/WNhvzvY/toallon.jpg'],
    "price": 3300,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
},
    {
    "name": "Bandera Selección",
    "description": "Bandera Selección Argentina.",
    "img": ['https://i.ibb.co/0Zh3hYR/bandera-Messi.jpg'],
    "price": 299,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
    "name": "Bolsa",
    "description": "Bolsa tela Selección Argentina.",
    "img": ['https://i.ibb.co/m9g097C/bolsa-Tela.jpg'],
    "price": 75,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
    "name": "Manta Selección",
    "description": "Manta Fluo AFA.",
    "img": ['https://i.ibb.co/sHHG0gg/manta-Fluorescente1.jpg'],
    "price": 6500,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
    "name": "Mate Selección",
    "description": "Material: Polipropileno BPA FREE. Medidas. Medidas Mate: 9,5cm de alto X 8cm de diametro. Medidas Totales: 12cm de alto X 7cm de diametro.",
    "img": ["https://i.ibb.co/80qLgJ3/mate-Tripode.jpg"],
    "price": 1200,
    "stock": 20,
    "category": ["Bazar"],
    "review": [],
    },
    {
        "name": "LLavero Selección",
    "description": "MATERIAL: ZAMAK (aleación zinc con aluminio, magnesio y cobre).",
    "img": ["https://i.ibb.co/BBPdSQL/destapador1.jpg"],
    "price": 650,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
        "name": "Caramagnola Selección",
    "description": "ERGONÓMICA. MATERIAL: POLIPROPILENO BPA FREE. CAPACIDAD: 700 CC. ALTURA: 22,5 cm. DIAMETRO: 7 cm.",
    "img": ["https://i.ibb.co/4mhXD3Q/caramagnola.jpg"],
    "price": 420,
    "stock": 20,
    "category": ["Bazar"],
    "review": [],
    },
    {
        "name": "Vaso Termico Selección",
    "description": "PICO VERTEDOR. CAPACIDAD: 500 ml. MEDIDAS: 16 cm (alto) x 9 cm (diámetro). MATERIAL: POLIPROPILENO.",
    "img": ["https://i.ibb.co/VNxPZZp/vaso-Termico.jpg"],
    "price": 680,
    "stock": 20,
    "category": ["Bazar"],
    "review": [],
    },
    {
        "name": "Pelota Adidas n5 Oficial Selección Argentina",
    "description": "¿Dónde terminará el viaje? Alentá a Argentina en el torneo de fútbol más importante del mundo. Esta pelota adidas luce el escudo oficial de la selección. Su diseño te ofrece un toque suave y una gran resistencia al desgaste. La cámara de butilo la mantiene inflada mientras vos jugás como tus héroes.",
    "img": ["https://i.ibb.co/rp0Xxvd/pelota-Afa.jpg"],
    "price": 9999,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
        "name": "Pelota Adidas n5 Competición Selección Argentina",
    "description": "Pelota N°5 Adidas Competición Selección Argentina - Temporada 2021.",
    "img": ["https://i.ibb.co/R6Rs31w/pelota-Afa-Competicion1.jpg"],
    "price": 23999,
    "stock": 20,
    "category": ["Accesorios"],
    "review": [],
    },
    {
        "name": "Camiseta de Entrenamiento Adidas AFA Selección Argentina Verde",
    "description": "Camiseta de Entrenamiento Verde 2020. Te presentamos la nueva camiseta de entrenamiento de la selección Argentina en color verde. Indumentaria oficial de AFA para la Copa América 2020.",
    "img": ["https://i.ibb.co/f4JP0mJ/camiseta-Entrenamiento1.jpg"],
    "price": 9999,
    "stock": 20,
    "category": ["Indumentaria"],
    "review": [],
    },
    {
        "name": "Chaleco Adidas AFA Selección Argentina",
    "description": "Chaleco Adidas Reversible 2020. Presentamos el nuevo chaleco reversible oficial de la Selección Argentina de Futbol . Indumentaria oficial AFA para la Copa América 2020.",
    "img": ["https://i.ibb.co/9pdc1Nv/chaleco-Seleccion1.jpg"],
    "price": 23999,
    "stock": 20,
    "category": ["Indumentaria"],
    "review": [],
    },
    {
    "name": "Camiseta Titular Adidas Messi AFA Selección Argentina",
    "description": "100% Argentina. Diseñada para los hinchas, ofrece comodidad en todo momento gracias a su tejido suave con tecnología de absorción AEROREADY. Los detalles en la parte interior trasera del cuello están inspirados en la bandera nacional que los jugadores representan con tanto orgullo. Un producto hecho parcialmente con contenido reciclado generado a partir de desechos de producción, tales como recortes de tela, y desechos domésticos postconsumo, para evitar un mayor impacto ambiental al producir contenido virgen.",
    "img": ["https://i.ibb.co/B49Ffpf/camiseta-Messi.jpg"],
    "price": 19999,
    "stock": 20,
    "category": ["Indumentaria"],
    "review": [],
    },
    {
        "name": "Camiseta Adidas Titular AFA Selección Argentina 2022",
        "description": "100% Argentina. Diseñada para los hinchas, ofrece comodidad en todo momento gracias a su tejido suave con tecnología de absorción AEROREADY. Los detalles en la parte interior trasera del cuello están inspirados en la bandera nacional que los jugadores representan con tanto orgullo. Un producto hecho parcialmente con contenido reciclado generado a partir de desechos de producción, tales como recortes de tela, y desechos domésticos postconsumo, para evitar un mayor impacto ambiental al producir contenido virgen.",
        "img": ["https://i.ibb.co/Z68z1zJ/camiseta-Seleccion1.jpg"],
        "price": 16999,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
    {
        "name": "Short Adidas Home Selección Argentina",
        "description": "SHORTS TITULARES PARA HINCHAS DE ARGENTINA. Bicampena del mundo, la Selección Argentina siempre sedienta de una nueva conquista. Usá estos shorts de fútbol adidas con la camiseta titular para lucir el mismo look de los jugadores en la cancha. Con tecnología AEROREADY que te asegura uan alta performance en el partido.",
        "img": ["https://i.ibb.co/JKWLZfD/short-Titular1.jpg"],
        "price": 6999,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
    {
        "name": "Camiseta Adidas Alternativa AFA Selección Argentina 2022",
        "description": "UNA CAMISETA DE VISITANTE DE ARGENTINA INSPIRADA EN LOS PAISAJES DEL PAIS AUSTRAL. Dedicada a la tierra que nos hace soñar. El uniforme alternativo de Argentina es un emblema pintado en tonos azules que refleja el esplendor de los glaciares del país. Esta camiseta oficial se encarga del calor y el sudor gracias a su tejido transpirable que es tan suave como la seda. El escudo de la selección y los detalles están estampados por termotransferencia para una mayor ligereza en la cancha.",
        "img": ["https://i.ibb.co/YRXRK0j/camiseta-Alternativa1.jpg"],
        "price": 20299,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
    {
        "name": "Camiseta Mujer Adidas Alternativa AFA Selección Argentina 2022",
        "description": "Dedicada a la tierra que nos hace soñar. El kit de visitante de Argentina es un emblema pintado en tonos azules que reflejan el esplendor de los glaciares del país. Demostrá tu pasión por la selección nacional con esta camiseta de fútbol adidas. Diseñada para los verdaderos hinchas, esta versión de la camiseta oficial luce el escudo de la selección tejido en el pecho. El suave tejido absorbe la humedad para mantenerte seco del estadio a las calles.",
        "img": ["https://i.ibb.co/K06gbqF/camiseta-Mujer-Alternativa.jpg"],
        "price": 11199,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
    {
        "name": "Camiseta Infatil Adidas Messi AFA Selección Argentina 2022",
        "description": "100% Argentina. Diseñada para los hinchas, ofrece comodidad en todo momento gracias a su tejido suave con tecnología de absorción AEROREADY. Los detalles en la parte interior trasera del cuello están inspirados en la bandera nacional que los jugadores representan con tanto orgullo. Un producto hecho parcialmente con contenido reciclado generado a partir de desechos de producción, tales como recortes de tela, y desechos domésticos postconsumo, para evitar un mayor impacto ambiental al producir contenido virgen.",
        "img": ["https://i.ibb.co/zSySC55/camiseta-Nino-Titular.jpg"],
        "price": 17199,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
    {
        "name": "Short Alternativo Adidas Messi AFA Selección Argentina 2022",
        "description": "Luciendo el clásico color blanco, este short de fútbol adidas de la Selección Argentina sigue el ejemplo de la camiseta a la que acompañan. Creado para mantener cómodo al hincha, están hechos de tejido suave y cuentan con tecnología de absorción AEROREADY. EL logo de la selección bordado le pone el toque final al diseño. Hecho con materiales 100% reciclados, este producto representa solo una de nuestras soluciones para acabar con los residuos plásticos.",
        "img": ["https://i.ibb.co/d7fmNn3/short-Alternativo.jpg"],
        "price": 9999,
        "stock": 20,
        "category": ["Indumentaria"],
        "review": [],
    },
]